# Generated by Django 3.1.6 on 2021-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(help_text='Máximo 30 caracteres', max_length=30, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='chassi',
            name='numero',
            field=models.CharField(help_text='Máximo 16 caracteres', max_length=16, verbose_name='Chassi'),
        ),
    ]
